export const {
    REACT_APP_FIREBASE_API_KEY,
    REACT_APP_AUTH_DOMAIN,
    REACT_APP_DATABASE_URL,
    REACT_APP_PROJECT_ID,
    REACT_APP_FIREBASE_STORAGE_BUCKET,
    REACT_APP_FIREBASE_MESSAGING_ID,
    REACT_APP_FIREBASE_APP_ID,
    REACT_APP_MEASUREMENT_ID,


    REACT_APP_FIRESTORE_COURSES_COLLECTION,
    REACT_APP_FIRESTORE_COURSES_DOCUMENT,
    REACT_APP_FIRESTORE_TESTIMONIAL_COLLECTION,
    REACT_APP_FIRESTORE_TESTIMONIAL_DOCUMENT,
    REACT_APP_STORAGE_GALLERY_DIRECTORY,
} = process.env;